import dotenv from 'dotenv';
dotenv.config();

import { sql } from 'kysely';
import { db } from "./database.ts";

export async function seed(): Promise<void> {
  console.log('Clearing existing data...');
  await sql`TRUNCATE TABLE users, tickets RESTART IDENTITY CASCADE`.execute(db);

  console.log('Seeding users...');
  const userSeeds = [
    { name: 'Alice Chen', email: 'alice.chen@example.com', password: 'password123' },
    { name: 'Bob Martinez', email: 'bob.martinez@example.com', password: 'password123' },
    { name: 'Charlie Kim', email: 'charlie.kim@example.com', password: 'password123' },
    { name: 'Dana Scott', email: 'dana.scott@example.com', password: 'password123' },
    { name: 'Evan Patel', email: 'evan.patel@example.com', password: 'password123' },
  ] as const;

  const users = await db
    .insertInto('users')
    // IDs and timestamps are generated by the database; exclude them from inserts.
    .values(userSeeds as any)
    .returningAll()
    .execute();

  const [u1, u2, u3, u4, u5] = users;

  console.log('Seeding tickets...');
  const tickets = [
    {
      title: 'Implement OAuth2 login with Google',
      description:
        'Allow users to authenticate using their corporate Google accounts.',
      status: 'TODO',
      creator_id: u1.id,
      assignee_id: u2.id,
    },
    {
      title: 'Fix race condition in ticket assignment',
      description:
        'Concurrent assignments occasionally overwrite status updates.',
      status: 'IN_PROGRESS',
      creator_id: u2.id,
      assignee_id: u3.id,
    },
    {
      title: 'Set up Redis cache for user session store',
      description: 'Improve session retrieval latency under heavy traffic.',
      status: 'DONE',
      creator_id: u3.id,
      assignee_id: u1.id,
    },
    {
      title: 'Refactor database connection pool settings',
      description: 'Tune max connections and idle timeout for production load.',
      status: 'TODO',
      creator_id: u1.id,
      assignee_id: null,
    },
    {
      title: 'Add pagination support to tickets endpoint',
      description: 'Support limit and offset query parameters on GET /tickets.',
      status: 'IN_PROGRESS',
      creator_id: u4.id,
      assignee_id: u4.id,
    },
    {
      title: 'Design dashboard analytics wireframes',
      description:
        'Create Figma mocks for sprint burndown and velocity charts.',
      status: 'DONE',
      creator_id: u5.id,
      assignee_id: u5.id,
    },
    {
      title: 'Resolve memory leak in WebSocket connection handler',
      description:
        'Stale socket listeners are not cleaned up on client disconnect.',
      status: 'TODO',
      creator_id: u2.id,
      assignee_id: u3.id,
    },
    {
      title: 'Write automated integration tests for authentication',
      description:
        'Cover token validation, expiry, and missing credential paths.',
      status: 'IN_PROGRESS',
      creator_id: u3.id,
      assignee_id: u2.id,
    },
    {
      title: 'Upgrade Node.js runtime to version 24 LTS',
      description:
        'Update base Docker images and verify package compatibility.',
      status: 'DONE',
      creator_id: u1.id,
      assignee_id: u1.id,
    },
    {
      title: 'Implement rate limiting middleware for public API',
      description: 'Throttle client requests to 100 per minute per IP address.',
      status: 'TODO',
      creator_id: u4.id,
      assignee_id: null,
    },
    {
      title: 'Fix CSS overflow bug on mobile ticket details modal',
      description:
        'Modal body content is clipped on viewports narrower than 400px.',
      status: 'TODO',
      creator_id: u5.id,
      assignee_id: u2.id,
    },
    {
      title: 'Configure automated database backup pipeline',
      description:
        'Nightly pg_dump snapshots shipped to encrypted cloud storage.',
      status: 'DONE',
      creator_id: u1.id,
      assignee_id: u3.id,
    },
    {
      title: 'Create OpenAPI / Swagger documentation specification',
      description:
        'Document all REST endpoints and schemas for consumer teams.',
      status: 'IN_PROGRESS',
      creator_id: u2.id,
      assignee_id: u4.id,
    },
    {
      title: 'Add email notification on ticket status change',
      description:
        'Send transactional emails when tickets move to DONE or BLOCKED.',
      status: 'TODO',
      creator_id: u3.id,
      assignee_id: null,
    },
    {
      title: 'Optimize slow SQL queries on ticket listing query',
      description: 'Add composite indices for status and created_at columns.',
      status: 'DONE',
      creator_id: u4.id,
      assignee_id: u1.id,
    },
    {
      title: 'Implement audit logging for administrative actions',
      description: 'Log user deletions and role escalations to security trail.',
      status: 'TODO',
      creator_id: u1.id,
      assignee_id: u5.id,
    },
    {
      title: 'Fix CORS policy header configuration for staging environment',
      description:
        'Allow credentials and explicit frontend origin in preflight.',
      status: 'DONE',
      creator_id: u2.id,
      assignee_id: u2.id,
    },
    {
      title: 'Support markdown formatting in ticket descriptions',
      description: 'Render code blocks, lists, and inline links safely in UI.',
      status: 'IN_PROGRESS',
      creator_id: u3.id,
      assignee_id: u3.id,
    },
    {
      title: 'Add health check endpoint for container orchestration',
      description: 'Expose GET /health with database connectivity status.',
      status: 'DONE',
      creator_id: u4.id,
      assignee_id: u4.id,
    },
    {
      title: 'Implement time tracking feature for billing reports',
      description:
        'Allow team members to record hours spent on individual tickets.',
      status: 'TODO',
      creator_id: u5.id,
      assignee_id: u2.id,
    },
    {
      title: 'Fix date parsing discrepancy on UTC timestamps',
      description:
        'Ensure consistent ISO-8601 formatting across client timezones.',
      status: 'IN_PROGRESS',
      creator_id: u1.id,
      assignee_id: u5.id,
    },
    {
      title: 'Create dark mode theme toggle for client application',
      description:
        'Persist theme preference in localStorage and synchronize CSS variables.',
      status: 'TODO',
      creator_id: u2.id,
      assignee_id: null,
    },
    {
      title: 'Configure Prometheus metrics exporter for API latency',
      description:
        'Expose request count, duration histograms, and error rates.',
      status: 'DONE',
      creator_id: u3.id,
      assignee_id: u1.id,
    },
    {
      title: 'Sanitize user inputs to prevent stored XSS attacks',
      description:
        'Strip script tags and escape HTML entities on comment creation.',
      status: 'TODO',
      creator_id: u4.id,
      assignee_id: u3.id,
    },
    {
      title: 'Add bulk ticket export to CSV feature',
      description:
        'Generate streaming CSV downloads for filtered ticket lists.',
      status: 'TODO',
      creator_id: u5.id,
      assignee_id: null,
    },
  ];

  await db
    .insertInto('tickets')
    // IDs and timestamps are generated by the database; exclude them from inserts.
    .values(tickets as any)
    .execute();

  console.log(
    `Seeded ${users.length} users and ${tickets.length} tickets successfully.`,
  );
}

// Run directly from CLI
if (process.argv[1]?.includes('seed')) {
  seed()
    .then(() => db.destroy())
    .catch((err) => {
      console.error('Failed to seed database:', err);
      process.exit(1);
    });
}
